server:
  port: 8081
spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/web_java_course_final_project_db}
    username: ${DB_USERNAME:dev}
    password: ${DB_PASSWORD:password}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret-key: ${JWT_SECRET_KEY:secret}
  validity-in-ms: ${JWT_VALIDITY_IN_MS:3600000} # default is 1 hour

authentication:
  max-failed-logins: 5