server:
  port: 8081
spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/web_java_course_final_project_db}
    username: ${DB_USERNAME:dev}
    password: ${DB_PASSWORD:password}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    protocol: smtp
    host: ${EMAIL_HOST:127.0.0.1}
    port: ${EMAIL_PORT:25}
    username: ${EMAIL:any}
    password: ${EMAIL_PASSWORD:any}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret-key: ${JWT_SECRET_KEY:secret}
  validity-in-ms: ${JWT_VALIDITY_IN_MS:3600000} # default is 1 hour

authentication:
  max-failed-logins: 5

password-reset-settings:
  token-expiration_duration: PT1H
  url: "static/reset_password.html"

url-processor:
  scheme: ${SCHEME:http}
  host: ${HOST:localhost}
  port: ${PORT:8081}